### ISSUE TITLE
Default media type of documents

### ISSUE THREAD

**Issue by jonathanrobie** [distributed-text-services/distributed-text-services.github.io#4]
Thibault proposes that the default media type of a document should be 'The default format of answer should be `application/tei+xml `, leaving other media types to the implementation.

**Comment by jonathanrobie** [comment]
I think that the media type should be determined by standard [HTTP content negotiation](https://www.w3.org/Protocols/rfc2616/rfc2616-sec12.html).  A server should give the most precise media type that a client is willing to accept for a given document, based on its knowledge of the document.  If the most precise type of a document is `application/tei+xml`, that is the media type that the server will provide unless the client provides `ACCEPT` headers that do not allow this type.  But not all documents are TEI.

**Comment by PonteIneptique** [comment]
> I think that the media type should be determined by standard HTTP content negotiation. 

I agree.

>  But not all documents are TEI.

I don't "agree" :). This is where I think we need to enforce this thing.

One of the failure of CTS was to accept as many schemes as there is implementations, without enforcing any kind of correct format. This would lead to not knowing how to parse the content, to not being really able to foresee what you would get. We have the chance to have a format for textual edition : TEI. Right now, there is not a single standard API (as far as I know) that relies on it. We discussed this a while ago and while I think we should allow implementers to provide other mimetypes, I think XML/TEI should always be accessible. 

One of the reason for this, unlike images (I look kindly at you, IIIF) and structured metadata, is that textual edition is broad, wide, and should I say wide enough to be already complex in TEI. When you query most standard LOD APIs, you can expect to get RDF, in different kind of expression : json-ld, xml/rdf, turtle, etc.  We do not have the same standard for textual edition. HTML, raw text, csv, non grammar based xml, etc. are way too different to be treated the same way.

Having TEI, a scholarly accepted standard, as a standard and obligatory output, is required for the API to really have an impact for these reasons. Let's be clear in terms of implementation duties : the server must have the ability to reply a valid content to `Accept: application/tei+xml` and can expand to other mime.

**Comment by jonathanrobie** [comment]
Suppose I want to serve syntax trees in a format that is semantically different from TEI's standard. I cannot really convert that to a TEI format, and doing so would require effort for the data producer.  If both the producer and the consumer want that format for these documents, do they need to use a different protocol?

**Comment by PonteIneptique** [comment]
Any format transformation in the case of text serving is a loss of
information. Serving syntax tree has never been the focus of DTS, and has
never been discussed as such. This is for example not a use case or user
story we had set up at the beginning of our discussion.

As such, and to be clear, I am not against tree serving, but historically,
we already discussed the format of xml tei to be the standard. Otherwise,
it makes no sense to differentiate ourselves from other initiatives. Any
data transformation would require effort, but if you are willing to deploy
the API and do not have tei, then you have to pay this entry fee.

I do not believe it will be that complicated to transform part of the
content, with loss or gain, into tei.

Le 9 sept. 2017 11:14 PM, "Jonathan Robie" <notifications@github.com> a
écrit :

Suppose I want to serve syntax trees in a format that is semantically
different from TEI's standard. I cannot really convert that to a TEI
format, and doing so would require effort for the data producer. If both
the producer and the consumer want that format for these documents, do they
need to use a different protocol?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/distributed-text-services/distributed-text-services.github.io/issues/4#issuecomment-328303874>,
or mute the thread

**Comment by jonathanrobie** [comment]
DTS is a replacement for CTS, which is  not restricted to TEI.

I don't know what level of design decision has been made on this.  I was not aware of a firm decision, but there may have been one.  We'll discuss in the meeting.

**Comment by PonteIneptique** [comment]
> DTS is a replacement for CTS, which is not restricted to TEI.

I agree. And CTS has been a failing API also by not providing clear contents type restriction (or base content type) which led to having really few API that can be parsed.

> I don't know what level of design decision has been made on this. I was not aware of a firm decision, but there may have been one. We'll discuss in the meeting.

There was no hard decision written in stones, but I definitely remember a meeting where this was discussed, we clearly leaned towards at least TEI as the basis, potentially to propose this whole work to TEI-C, and even assigned the poor @hcayless to the passage endpoint discussing chairing (at the time where we had multiple chairs).

**Comment by PonteIneptique** [comment]
To recap and build on some discussion #9 out of two comments from @hcayless ( [1](https://github.com/distributed-text-services/distributed-text-services.github.io/issues/9#issuecomment-329482590) [2](https://github.com/distributed-text-services/distributed-text-services.github.io/issues/9#issuecomment-329483267) ) : 

## What we could  at least, make the following rules: 
- A DTS API *should* be able to reply with `application/tei+xml` content on the passage/document endpoint(s)
- A DTS API *can* serve any other content types (See below)
- The response *should* be well-formed XML
- The response *could* either be a full TEI document or a fragment (See below)
- The response *can* be expected to be valid TEI, though it is not required 

## Fragment 
A `fragment` could be either a new node, proposed to TEI, or an already existing node (`ab` was proposed on the TEI List ( http://tei-l.970651.n3.nabble.com/Returning-fragments-from-TEI-documents-td4030077.html ). If we were to adopt this requirement for the API, we would need to discuss the proposal of a `fragment` node to the TEI list and agree on it here (aka open a new issue)

## Other content types
There is a secondary question which could be : do we want to limit content types, *ie* should we forbid to reply with binary formats such as PDF or images (which are not "minable") ? 

I have no specific point of view on the question but it felt like a question that can be asked.

**Comment by balmas** [comment]
This issue was moved to distributed-text-services/collection-api#70
