### ISSUE TITLE
Navigation API

### ISSUE THREAD

**Issue by jonathanrobie** [distributed-text-services/distributed-text-services.github.io#7]
The navigation API needs to be completed.

**Comment by PonteIneptique** [comment]
A first draft was proposed in my amended version : https://github.com/distributed-text-services/distributed-text-services.github.io/wiki/Distributed-Text-Services-API-Proposal-Thibault-Amends#navigation-todo


### Query Parameters

| name | description                              | methods |
|------|------------------------------------------|---------|
| id   | identifier for a document |  GET    |
| passage | passage identifier (used together with `id`) | GET    |
| level | Depth for passages we want to retrieve identifiers of  | GET    |

### Response Headers

The answer comes with the following headers :

| name | description |
|------|-------------|
| Link | Gives relation to next and previous pages |

**Comment by PonteIneptique** [comment]
In issue #9 , @jonathanrobie and @hcayless have mentioned directions : 

> ancestors, parent, siblings, following siblings, preceding siblings, or all descendants

I see the following list of parameters, adding on top of the direction "children"

| Name | Description                              | Methods |
|------|------------------------------------------|---------|
| level | (default = 0) Depth for passages we want to retrieve identifiers of  | GET    |
| type  | (Optional) Type of the level to filter one, whatever the depth is. Types are declared in collection's metadata   | GET    |
| direction | (Default : children) Direction in which to retrieve  | GET    |
| groupby | (Optional) Create range of references  | GET    |
| limit | (Optional) Limits the number of result  | GET    |
| semantic | (Optional) Retrieve the typename of the passages as well as the passage reference  | GET    |

Note : urn:cts:greekLit:tlg0012.tlg001.opp-grc5 is the Iliad

- GET `/dts/api/references/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc5` returns the list of reference available at `depth=0` and `direction=children`. This would be the list of books of the Iliad
- GET `/dts/api/references/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc5&passage=1` returns the list of reference available at `depth=0` and `direction=children` of `passage=1`. This would be the list of verses of the Iliad (In this option, depth is relative. We can set it to be absolute)
- GET `/dts/api/references/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc5&type=verse&direction=descendants&groupby=30` returns the list of all passages that are verse and would group them by 30.

**Comment by PonteIneptique** [comment]
Response could be built around 

- GET `/dts/api/references/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc5&passage=1` 

```json
{
    "@base": "/dts/api/document/",
    "@id":"urn:cts:greekLit:tlg0012.tlg001.perseus-grc2",
    "passage": ["1.1",  "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "1.10", "1.11", "1.12",  "1.13", "1.14", "1.15",  "1.16", "1.17", "1.18", "1.19", "1.20", "1.21", "1.22", "1.23", "1.24", "1.25", "1.26", "1.27", "1.28", "1.29", "1.30", "1.31", "1.32", "1.33", "1.34", "1.35"]
}
```
- GET `/dts/api/references/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc5&limit=10&direction=descendants&semantic` 

```json
{
    "@base": "/dts/api/document/",
    "@id":"urn:cts:greekLit:tlg0012.tlg001.perseus-grc2",
    "passage": [
        {"@type": "book", "@id": "1"},
        {"@type": "verse", "@id": "1.1"},
        {"@type": "verse", "@id": "1.2"},
        {"@type": "verse", "@id": "1.3"},
        {"@type": "verse", "@id": "1.4"},
        {"@type": "verse", "@id": "1.5"},
        {"@type": "verse", "@id": "1.6"},
        {"@type": "verse", "@id": "1.7"},
        {"@type": "verse", "@id": "1.8"},
        {"@type": "verse", "@id": "1.9"},
    ]
}
```

**Comment by balmas** [comment]
This issue was moved to distributed-text-services/collection-api#68
